apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: governance-policy-propagator-krug
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: governance-policy-propagator-krug
    app.kubernetes.io/part-of: governance-policy-propagator
  name: governance-policy-propagator-krug
  namespace: dfodor-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: governance-policy-propagator-krug
status:
  loadBalancer: {}
